SELECT
S.SERVICELONGNAME AS  ServiceName,	
	
STE.SERVICETYPEEXTRANAME AS ExtraName,	
CR.CHILDRATEID AS CHILDRATEID,	
P.PRICEID AS PRICEID,     	
CR.CHILDRATEFROMAGE AS FROMAGE,	
CR.CHILDRATETOAGE AS TOAGE,	
CR.CHILDRATEAMOUNT AS AMOUNT,       	
CR.ADDITIONALCHILDRATEAMOUNT AS ADDN_AMOUNT

FROM SERVICE S
INNER JOIN SERVICE_EXTRA SE ON SE.SERVICEID= S.SERVICEID
INNER JOIN  PRICE P ON P.SERVICEEXTRAID= SE.SERVICEEXTRAID
LEFT JOIN CHILD_RATE CR ON CR.PRICEID = P.PRICEID
INNER JOIN SERVICE_TYPE_EXTRA STE ON STE.SERVICETYPEEXTRAID=SE.SERVICEEXTRAID


SELECT
S.SERVICELONGNAME  ServiceName,	
STO.SERVICETYPEOPTIONNAME AS  OptionName	,
CR.CHILDRATEID AS CHILDRATEID,	
P.PRICEID AS PRICEID,     	
CR.CHILDRATEFROMAGE AS FROMAGE,	
CR.CHILDRATETOAGE AS TOAGE,	
CR.CHILDRATEAMOUNT AS AMOUNT,       	
CR.ADDITIONALCHILDRATEAMOUNT AS ADDN_AMOUNT

FROM SERVICE S
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIN ON SOIN.SERVICEID=S.SERVICEID
INNER JOIN PRICE P ON P.SERVICEOPTIONINSERVICEID = SOIN.SERVICEOPTIONINSERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID=SOIN.SERVICETYPEOPTIONID
LEFT JOIN CHILD_RATE CR ON CR.PRICEID = P.PRICEID