SELECT *
--ServiceName	
--OptionName	
--ExtraName	
--CHILDRATEID 	
--PRICEID     	
--FROMAGE	
--TOAGE	
--AMOUNT       	
--ADDN_AMOUNT
FROM SERVICE S

INNER JOIN SERVICE_EXTRA SE ON SE.SERVICEID = S.SERVICEID 
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIS ON SOIS.SERVICEID = S.SERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO STO.


SELECT 
S.SERVICELONGNAME AS ServiceName,
STO.SERVICETYPEOPTIONNAME AS OptionName,
CR.CHILDRATEID AS ChildRate,
P.PRICEID AS PriceId,
CR.CHILDRATEFROMAGE AS FROMAGE,
CR.CHILDRATETOAGE TOAGE,
CR.CHILDRATEAMOUNT AS AMOUNT,
CR.ADDITIONALCHILDRATEAMOUNT ADDN_AMOUNT																									
FROM SERVICE S
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIS ON SOIS.SERVICEID=S.SERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID=SOIS.SERVICETYPEOPTIONID
INNER JOIN PRICE P ON P.SERVICEOPTIONINSERVICEID=SOIS.SERVICEOPTIONINSERVICEID
INNER JOIN CHILD_RATE CR ON CR.PRICEID=P.PRICEID