SELECT 
S.SERVICELONGNAME,	
SE.SERVICEEXTRAID,	
STE.SERVICETYPEEXTRAID,	
STE.SERVICETYPEEXTRANAME,	
SES.SERVICEEXTRASTATUSID,	
SERVICEEXTRASTATUSNAME
FROM SERVICE_EXTRA SE

INNER JOIN  SERVICE S ON S.SERVICEID = SE.SERVICEID
INNER JOIN  SERVICE_TYPE_EXTRA STE ON  STE.SERVICETYPEEXTRAID = SE.SERVICETYPEEXTRAID 
INNER JOIN  SERVICE_EXTRA_STATUS SES ON SES.SERVICEEXTRASTATUSID = SE.SERVICETYPEEXTRAID 

