SELECT 
MA.MASTERALLOCATIONID,	
MAU.MASTERALLOCATIONUSAGEDATE AS USAGEDATE,	
MAU.MASTERALLOCATIONUSAGETOTALQUANTITY AS TOTALQUANTITY,
MAU.MASTERALLOCATIONUSAGECLOSED AS CLOSED, 	
MA.MASTERALLOCATIONRELEASEPERIOD AS RELEASEPERIOD,
MAU.MASTERALLOCATIONUSAGEMAXLIMITFREESELL AS MAXLIMITFREESELL

FROM SERVICE S
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIS ON SOIS.SERVICEID = S.SERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = SOIS.SERVICETYPEOPTIONID
INNER JOIN ALLOCATION_MEMBERSHIP AM ON AM.SERVICEOPTIONINSERVICEID = SOIS.SERVICEOPTIONINSERVICEID
INNER JOIN MASTER_ALLOCATION MA ON MA.MASTERALLOCATIONID = AM.MASTERALLOCATIONID
INNER JOIN MASTER_ALLOCATION_USAGE MAU ON MAU.MASTERALLOCATIONID = MA.MASTERALLOCATIONID

SELECT * FROM SERVICE_OPTION_IN_SERVICE
SELECT * FROM ALLOCATION_MEMBERSHIP
SELECT * FROM SERVICE_TYPE_OPTION
SELECT * FROM MASTER_ALLOCATION
SELECT * FROM MASTER_ALLOCATION_USAGE