SELECT 
S.SERVICELONGNAME AS ServiceName,
MA.MASTERALLOCATIONID AS  MasterAllocationID,
MA.MASTERALLOCATIONOVERALLOCATABLE AS OVERALLOCATABLE,
MA.MASTERALLOCATIONOVERSOLD AS OVERSOLD,
MA.MASTERALLOCATIONFREESELLSALE AS FREESELLSALE,
MA.MASTERALLOCATIONFREESELLSALEOVERRIDE AS FREESELLSALEOVERRIDE,
S.SERVICECONTRACTOWNERID AS ContractID,
MA.MASTERALLOCATIONSTARTDATE AS STARTDATE,	
MA.MASTERALLOCATIONENDDATE AS  ENDDATE,    	
MA.MASTERALLOCATIONDAYMONDAY AS MONDAY,  
MA.MASTERALLOCATIONDAYTUESDAY  AS TUESDAY ,
MA.MASTERALLOCATIONDAYWEDNESDAY AS WEDNESDAY,
MA.MASTERALLOCATIONDAYTHURSDAY AS THURSDAY,
MA.MASTERALLOCATIONDAYFRIDAY AS FRIDAY,   	
MA.MASTERALLOCATIONDAYSATURDAY  AS SATURDAY , 
MA.MASTERALLOCATIONDAYSUNDAY  AS SUNDAY,  	
MA.MASTERALLOCATIONUNITSMON AS UNITSMON,
MA.MASTERALLOCATIONUNITSTUE AS UNITSTUE,
MA.MASTERALLOCATIONUNITSWED AS UNITSWED,
MA.MASTERALLOCATIONUNITSTHU AS UNITSTHU,
MA.MASTERALLOCATIONUNITSFRI AS UNITSFRI,
MA.MASTERALLOCATIONUNITSSAT AS UNITSSAT,
MA.MASTERALLOCATIONUNITSSUN AS UNITSSUN,
MA.MASTERALLOCATIONRELEASEPERIODMON AS RP_MON,
MA.MASTERALLOCATIONRELEASEPERIODTUE AS RP_TUE,
MA.MASTERALLOCATIONRELEASEPERIODWED AS RP_WED,
MA.MASTERALLOCATIONRELEASEPERIODTHU AS RP_THU,
MA.MASTERALLOCATIONRELEASEPERIODFRI AS RP_FRI,
MA.MASTERALLOCATIONRELEASEPERIODSAT AS RP_SAT,
MA.MASTERALLOCATIONRELEASEPERIODSUN AS RP_SUN

FROM SERVICE S
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIS ON SOIS.SERVICEID = S.SERVICEID
INNER JOIN ALLOCATION_MEMBERSHIP AM ON AM.SERVICEOPTIONINSERVICEID = SOIS.SERVICEOPTIONINSERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = SOIS.SERVICETYPEOPTIONID
INNER JOIN MASTER_ALLOCATION MA ON MA.MASTERALLOCATIONID = AM.MASTERALLOCATIONID

SELECT * FROM SERVICE_OPTION_IN_SERVICE
SELECT * FROM ALLOCATION_MEMBERSHIP
SELECT * FROM SERVICE_TYPE_OPTION
SELECT * FROM MASTER_ALLOCATION