SELECT
S.SERVICELONGNAME,	
SOS.SERVICEOPTIONINSERVICEID,	
STO.SERVICETYPEOPTIONID,	
STO.SERVICETYPEOPTIONNAME,	
SOS.SERVICEOPTIONSTATUSID,	
SOST.SERVICEOPTIONSTATUSNAME
FROM SERVICE S
INNER JOIN  SERVICE_OPTION_IN_SERVICE SOS ON SOS.SERVICEID = S.SERVICEID
INNER JOIN  SERVICE_OPTION_STATUS SOST ON  SOST.SERVICEOPTIONSTATUSID = SOS.SERVICEOPTIONSTATUSID
INNER JOIN  SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = SOS.SERVICETYPEOPTIONID
WHERE S.SERVICEID=1;

