SELECT
S.SERVICELONGNAME AS ServiceName,
STO.SERVICETYPEOPTIONNAME AS OptionName,
P.PRICEBUYING AS IsBuying,
BT.BOOKINGTYPENAME AS BookingTypeName,
PT.PRICETYPENAME AS PriceTypeName,	
CD.CONTRACTDURATIONID AS ContractDurationID,	
--SeasonTypeName,	
--FromDate,	
--ToDate,
P.PRICEDAYMONDAY AS Mon,
P.PRICEDAYTUESDAY AS Tue,	
P.PRICEDAYWEDNESDAY AS Wed,
P.PRICEDAYTHURSDAY AS Thu,
P.PRICEDAYFRIDAY AS Fri,
P.PRICEDAYSATURDAY AS Sat,
P.PRICEDAYSUNDAY AS Sun,
P.PRICEID AS PriceID, 
C.CURRENCYISOCODE AS CurrencyISO,
P.PRICEAMOUNT AS Amount,
--P. Verified,	
-- Charging, 
CP.CHILDPOLICYNAME AS PolicyName,		
CP.CHILDPOLICYNAME AS ChildPolicyName
FROM SERVICE S

INNER JOIN  SERVICE_OPTION_IN_SERVICE SOIS ON SOIS.SERVICEID = S.SERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = SOIS.SERVICETYPEOPTIONID
INNER JOIN CURRENCY C ON C.CURRENCYID =S.CURRENCYID
INNER JOIN PRICE P  ON P.CURRENCYID = C.CURRENCYID
INNER JOIN PRICE_TYPE PT ON PT.PRICETYPEID = P.PRICETYPEID
INNER JOIN CHILD_POLICY CP ON CP.CHILDPOLICYID = P.CHILDPOLICYID
INNER JOIN SEASON_TYPE ST ON ST.SEASONTYPEID = P.SEASONTYPEID
INNER JOIN BOOKING_TYPE BT ON BT.BOOKINGTYPEID = P.BOOKINGTYPEID
INNER JOIN CONTRACT_DURATION CD ON CD.CONTRACTDURATIONID = P.CONTRACTDURATIONID
INNER JOIN ASSIGNED_CHARGING_POLICY AP ON AP.SERVICETYPEOPTIONID = STO.SERVICETYPEOPTIONID
INNER JOIN CHARGING_POLICY CHRP ON CHRP.CHARGINGPOLICYID = AP.CHARGINGPOLICYID