SELECT
S.SERVICELONGNAME AS  ServiceName,	
STO.SERVICETYPEOPTIONNAME AS  OptionName,		
PB.PRICEBANDID, 	
P.PRICEID,     	
PB.PRICEBANDTYPEID, 	
PB.PRICEBANDMIN AS   MIN,	
PB.PRICEBANDMAX AS  MAX,	
PB.PRICEBANDGROSSAMOUNT AS  GROSS,	
P.PRICECOMMISSION AS   COMMISSION,	
P.PRICEAMOUNT AS AMOUNT       
FROM SERVICE S
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIS ON SOIS.SERVICEID = S.SERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = SOIS.SERVICETYPEOPTIONID
INNER JOIN PRICE P ON P.SERVICEOPTIONINSERVICEID = SOIS.SERVICEOPTIONINSERVICEID
INNER JOIN PRICE_BAND PB ON PB.PRICEID = P.PRICEID



SELECT
S.SERVICELONGNAME AS ServiceName,		
STE.SERVICETYPEEXTRANAME AS ExtraName,	
PB.PRICEBANDID, 	
P.PRICEID,     	
PB.PRICEBANDTYPEID, 	
PB.PRICEBANDMIN AS MIN,	
PB.PRICEBANDMAX AS MAX,	
PB.PRICEBANDGROSSAMOUNT AS GROSS,	
P.PRICECOMMISSION AS COMMISSION,	
P.PRICEAMOUNT AS AMOUNT       
FROM SERVICE S
INNER JOIN SERVICE_EXTRA SE ON SE.SERVICEID = S.SERVICEID
INNER JOIN SERVICE_TYPE_EXTRA STE ON STE.SERVICETYPEEXTRAID = SE.SERVICETYPEEXTRAID
INNER JOIN PRICE P ON P.SERVICEEXTRAID = SE.SERVICEEXTRAID
LEFT JOIN PRICE_BAND PB ON PB.PRICEID = P.PRICEID