SELECT
S.SERVICEID,
S.SERVICELONGNAME,
S.SERVICESHORTNAME,
SUP.SUPPLIERID,
SUP.SUPPLIERNAME,	
SS.SERVICESTATUSID,
SS.SERVICESTATUSNAME,
ST.SERVICETYPEID,	
ST.SERVICETYPENAME

from SERVICE S 
INNER JOIN  SUPPLIER SUP ON SUP.SUPPLIERID=S.SUPPLIERID
INNER JOIN SERVICE_STATUS SS ON SS.SERVICESTATUSID = S.SERVICESTATUSID	
INNER JOIN SERVICE_TYPE ST ON ST.SERVICETYPEID = S.SERVICETYPEID
WHERE S.SERVICEID=1; 

SELECT * from SERVICE;
SELECT * from SUPPLIER;
SELECT * FROM SERVICE_STATUS;
SELECT * FROM SERVICE_TYPE;


