SELECT *
--DepartureName	
--ServiceName	
--OptionName	
--ExtraName	
--IsOptional	
--ElementName	
--Qty	
--NoOfNights	
--StatusName	
--FromDay	
--ToDay	
--SplitPrice	
--StatusName	
--IsActive
FROM PACKAGE P
INNER JOIN PACKAGE_DEPARTURE PD ON PD.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGEID =P.PACKAGEID
INNER JOIN SERVICE S ON S.SERVICEID = PS.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.PACKAGESERVICEID = PS.PACKAGESERVICEID
INNER JOIN PACKAGE_ELEMENT PE ON PE.PACKAGEID = P.PACKAGEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID =PE.SERVICETYPEOPTIONID
INNER JOIN BOOKED_OPTION_STATUS BOS ON BOS.BOOKEDOPTIONSTATUSID =PO.BOOKEDOPTIONSTATUSID
