SELECT 
PD.PACKAGEDEPARTURENAME AS DepartureName,	
PID.PACKAGEITINERARYDAYID AS Day,	
PID.PACKAGEITINERARYDAYDESCRIPTION AS DayDesc,
PII.PACKAGEITINERARYITEMID AS Item,
PII.PACKAGEITINERARYITEMSEQ AS ItemSeq,
PII.PACKAGEITINERARYITEMDESCRIPTION AS ItemDesc,	
S.SERVICELONGNAME AS ServiceName,
STO.SERVICETYPEOPTIONNAME AS OptionName,
STE.SERVICETYPEEXTRANAME AS ExtraName,	
PO.PACKAGEOPTIONOPTIONAL IsOptional,	
PE.BASEDONPACKAGEELEMENTID AS ElementName,	
PO.PACKAGEOPTIONQUANTITY Qty,
PO.PACKAGEOPTIONNUMBEROFNIGHTS AS NoOfNights,
--BOS.BOOKEDOPTIONSTATUSNAME AS StatusName,	
PO.PACKAGEOPTIONFROMDAYSEQ AS FromDay,	
PO.PACKAGEOPTIONTODAYSEQ AS ToDay,
PO.PACKAGEOPTIONSPLITPRICE AS SplitPrice,
P.SERVICE_AVAILABILITY AS IsActive
FROM PACKAGE P
INNER JOIN PACKAGE_STATUS PS ON PS.PACKAGESTATUSID = P.PACKAGESTATUSID
INNER JOIN PACKAGE_DEPARTURE PD ON PD.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_DEPARTURE_STATUS PDS ON PDS.PACKAGEDEPARTURESTATUSID =PD.PACKAGEDEPARTURESTATUSID
INNER JOIN PACKAGE_ITINERARY_DAY PID ON PID.PACKAGEDEPARTUREID = PD.PACKAGEDEPARTUREID
INNER JOIN PACKAGE_ITINERARY_ITEM PII ON PII.PACKAGEITINERARYDAYID = PID.PACKAGEITINERARYDAYID
INNER JOIN ASSIGNED_PACKAGE_SERVICE APS ON APS.PACKAGEITINERARYITEMID = PII.PACKAGEITINERARYITEMID
INNER JOIN PACKAGE_SERVICE PSE ON PSE.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_OPTION PO ON PSE.PACKAGESERVICEID = PO.PACKAGESERVICEID

INNER JOIN SERVICE S ON S.SERVICEID = PSE.SERVICEID
INNER JOIN PACKAGE_ELEMENT PE ON PE.PACKAGEELEMENTID = PO.PACKAGEELEMENTID 
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = PE.SERVICETYPEOPTIONID
INNER JOIN SERVICE_TYPE_EXTRA STE ON STE.SERVICETYPEID = S.SERVICETYPEID



