SELECT *
--DepartureName	
--Day	
--DayDesc	
--Item	
--ItemSeq	
--ItemDesc	
--ServiceName	
--OptionName	
--ExtraName	
--IsOptional	
--ElementName	
--Qty	
--NoOfNights	
--StatusName	
--FromDay	
--ToDay	
--SplitPrice	
--StatusName	
--IsActive
FROM PACKAGE P
INNER JOIN PACKAGE_STATUS PS ON PS.PACKAGESTATUSID = P.PACKAGESTATUSID
INNER JOIN PACKAGE_DEPARTURE PD ON PD.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_DEPARTURE_STATUS PDS ON PDS.PACKAGEDEPARTURESTATUSID =PD.PACKAGEDEPARTURESTATUSID
INNER JOIN PACKAGE_ITINERARY_DAY PID ON PID.PACKAGEDEPARTUREID = PD.PACKAGEDEPARTUREID
INNER JOIN PACKAGE_ITINERARY_ITEM PII ON PII.PACKAGEITINERARYDAYID = PID.PACKAGEITINERARYDAYID
INNER JOIN ASSIGNED_PACKAGE_SERVICE APS ON APS.PACKAGEITINERARYITEMID = PII.PACKAGEITINERARYITEMID
INNER JOIN PACKAGE_SERVICE PSE ON PSE.PACKAGEID = P.PACKAGEID
--INNER JOIN SERVICE S ON S.SERVICEID = P.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PSE.PACKAGESERVICEID = PO.PACKAGESERVICEID


