SELECT 
PD.PACKAGEDEPARTURENAME AS DepartureName,	
S.SERVICELONGNAME AS ServiceName,	
STO.SERVICETYPEOPTIONNAME AS OptionName,
STE.SERVICETYPEEXTRANAME AS ExtraName,	
PO.PACKAGEOPTIONOPTIONAL IsOptional,	
PE.BASEDONPACKAGEELEMENTID AS ElementName,
PO.PACKAGEOPTIONQUANTITY AS Qty,
PO.PACKAGEOPTIONNUMBEROFNIGHTS AS NoOfNights,	
BOS.BOOKEDOPTIONSTATUSNAME AS StatusName,	
PO.PACKAGEOPTIONFROMDAYSEQ AS FromDay,	
PO.PACKAGEOPTIONTODAYSEQ AS ToDay,
PO.PACKAGEOPTIONSPLITPRICE AS SplitPrice,	
BOS.BOOKEDOPTIONSTATUSNAME AS StatusName,	
P.SERVICE_AVAILABILITY AS IsActive

FROM PACKAGE P
INNER JOIN PACKAGE_DEPARTURE PD ON PD.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGEID =P.PACKAGEID
INNER JOIN SERVICE S ON S.SERVICEID = PS.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.PACKAGESERVICEID = PS.PACKAGESERVICEID
INNER JOIN PACKAGE_ELEMENT PE ON PE.PACKAGEID = P.PACKAGEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID =PE.SERVICETYPEOPTIONID
INNER JOIN BOOKED_OPTION_STATUS BOS ON BOS.BOOKEDOPTIONSTATUSID =PO.BOOKEDOPTIONSTATUSID

INNER JOIN SERVICE_TYPE_EXTRA STE ON STE.SERVICETYPEID = S.SERVICETYPEID
