SELECT
P.PACKAGELONGNAME PackageName,
S.SERVICELONGNAME ServiceName,
STO.SERVICETYPEOPTIONNAME OptionName,
STE.SERVICETYPEEXTRANAME ExtraName,
PO.PACKAGEOPTIONOPTIONAL IsOptional,
--PE.PACKAGEELEMENT ElementName,
PO.PACKAGEOPTIONQUANTITY Qty,
PO.PACKAGEOPTIONNUMBEROFNIGHTS NoOfNights,
BOS.BOOKEDOPTIONSTATUSNAME StatusName,
PO.PACKAGEOPTIONFROMDAYSEQ FromDay,
PO.PACKAGEOPTIONTODAYSEQ ToDay,
PO.PACKAGEOPTIONSPLITPRICE SplitPrice,
P.SERVICE_AVAILABILITY IsActive

FROM PACKAGE P

INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGEID = P.PACKAGEID
INNER JOIN SERVICE S ON S.SERVICEID = PS.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.PACKAGESERVICEID = PS.PACKAGESERVICEID
INNER JOIN PACKAGE_ELEMENT PE ON PE.PACKAGEID = P.PACKAGEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = PE.SERVICETYPEOPTIONID
INNER JOIN BOOKED_OPTION_STATUS BOS ON BOS.BOOKEDOPTIONSTATUSID = PO.BOOKEDOPTIONSTATUSID
INNER JOIN SERVICE_TYPE_EXTRA STE ON STE.SERVICETYPEID = S.SERVICETYPEID

SELECT * FROM PACKAGE
SELECT * FROM ORGANISATION
SELECT * FROM PACKAGE_ELEMENT
SELECT * FROM PACKAGE_STATUS
SELECT * FROM PACKAGE_TYPE