SELECT
P.PACKAGELONGNAME PackageName,	
--ElementName,	
S.SERVICELONGNAME ServiceName,	
--Option_Extra_Name,		
PRI.PRICEID PriceID,	
PACKAGEPRICEHEADERID,	
PP.BOOKFROMDATE AS FromDate,
PP.BOOKTODATE AS ToDate,
BT.BOOKINGTYPENAME AS BookingTypeName,
PT.PRICETYPENAME AS	PriceTypeName,		
PRI.PRICEDAYSUNDAY AS Sun,	
PRI.PRICEDAYMONDAY AS Mon,
PRI.PRICEDAYTUESDAY AS Tue,
PRI.PRICEDAYWEDNESDAY AS Wed,
PRI.PRICEDAYTHURSDAY AS Thu,
PRI.PRICEDAYFRIDAY AS Fri,
PRI.PRICEDAYSATURDAY AS Sat,
C.CURRENCYNAME Currency	,
--Sell_Amount	,
P.SERVICE_AVAILABILITY IAvailable,
--P.PRICEAMOUNTVALIDATED Verified,
PP.PRODUCTCODEID AS PRODUCTCODEID,	
CANCELLATIONPOLICYName


FROM PACKAGE P
INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGEID= P.PACKAGEID
INNER JOIN SERVICE S ON S.SERVICEID= PS.SERVICEID
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIN ON SOIN.SERVICEID= S.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.SERVICEOPTIONINSERVICEID= SOIN.SERVICEOPTIONINSERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID= SOIN.SERVICETYPEOPTIONID
INNER JOIN PACKAGE_ELEMENT PE ON PE.SERVICETYPEOPTIONID = STO.SERVICETYPEOPTIONID
INNER JOIN PACKAGE_PRICE PP ON PP.PACKAGEELEMENTID=PE.PACKAGEELEMENTID
INNER JOIN BOOKING_TYPE BT ON BT.BOOKINGTYPEID= PP.BOOKINGTYPEID
INNER JOIN CURRENCY C ON C.CURRENCYID = S.CURRENCYID
INNER JOIN PRICE_TYPE PT ON PT.PRICETYPEID= PP.PRICETYPEID
INNER JOIN CANCELLATION_POLICY CP ON CP.CANCELLATIONPOLICYID= S.CANCELLATIONPOLICYID
INNER JOIN PRICE PRI ON PRI.SERVICEOPTIONINSERVICEID= SOIN.SERVICEOPTIONINSERVICEID








SELECT
P.PACKAGELONGNAME PackageName,	
--ElementName,	
S.SERVICELONGNAME ServiceName,
--Option_Extra_Name,		
PRI.PRICEID PriceID,	
PP.PACKAGEPRICEHEADERID PACKAGEPRICEHEADERID,		
PP.PACKAGEPRICEFROMDATE FromDate,	
PP.PACKAGEPRICETODATE ToDATE,	
BookingTypeName,		
PriceTypeName,		
PP.PACKAGEPRICESUNDAY AS Sun,	
PP.PACKAGEPRICEMONDAY AS Mon,
PP.PACKAGEPRICETUESDAY AS Tue,
PP.PACKAGEPRICEWEDNESDAY AS Wed,
PP.PACKAGEPRICETHURSDAY AS Thu,
PP.PACKAGEPRICEFRIDAY AS Fri,
PP.PACKAGEPRICESATURDAY AS Sat,
C.CURRENCYNAME Currency,
PP.PACKAGEPRICEAMOUNT Sell_Amount,
P.SERVICE_AVAILABILITY IAvailable,
PRI.PRICEAMOUNTVALIDATED Verified,
P.PRODUCTCODEID PRODUCTCODEID,	
CP.CANCELLATIONPOLICYNAME CANCELLATIONPOLICYName


FROM PACKAGE P
INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGEID= P.PACKAGEID
INNER JOIN SERVICE S ON S.SERVICEID= PS.SERVICEID
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIN ON SOIN.SERVICEID= S.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.SERVICEOPTIONINSERVICEID= SOIN.SERVICEOPTIONINSERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID= SOIN.SERVICETYPEOPTIONID
INNER JOIN PACKAGE_ELEMENT PE ON PE.SERVICETYPEOPTIONID = STO.SERVICETYPEOPTIONID
INNER JOIN PACKAGE_PRICE PP ON PP.PACKAGEELEMENTID=PE.PACKAGEELEMENTID
INNER JOIN BOOKING_TYPE BT ON BT.BOOKINGTYPEID= PP.BOOKINGTYPEID
INNER JOIN CURRENCY C ON C.CURRENCYID = S.CURRENCYID
INNER JOIN PRICE_TYPE PT ON PT.PRICETYPEID= PP.PRICETYPEID
LEFT JOIN CANCELLATION_POLICY CP ON CP.CANCELLATIONPOLICYID= S.CANCELLATIONPOLICYID
INNER JOIN PRICE PRI ON PRI.SERVICEOPTIONINSERVICEID= SOIN.SERVICEOPTIONINSERVICEID


SELECT * FROM PACKAGE
SELECT * FROM ORGANISATION
SELECT * FROM PACKAGE_ELEMENT
SELECT * FROM PACKAGE_STATUS
SELECT * FROM PACKAGE_TYPE