SELECT 
PAM.PACKAGEMASTERALLOCATIONID AS PACKAGEMASTERALLOCATIONID,		
PD.PACKAGEDEPARTUREDATE AS DepartureDate,		
S.ALLOCATIONRELEASETIME AS ReleasePeriod,	
PAD.PACKAGEALLOCATIONDEPARTURETOTALAVAILABLE AS TotalAvailable,
PAD.PACKAGEALLOCATIONDEPARTURETOTALUSED AS TotalUsed,
PAD.PACKAGEALLOCATIONDEPARTURETOTALAVAILABLEUNITS AS TotalUnitsAvailable,		
PAD.PACKAGEALLOCATIONDEPARTURETOTALUSEDUNITS AS TotalUnitsUsed

FROM PACKAGE P
INNER JOIN PACKAGE_DEPARTURE PD ON PD.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGEDEPARTUREID = PD.PACKAGEDEPARTUREID
INNER JOIN SERVICE S ON S.SERVICEID = PS.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.PACKAGESERVICEID = PS.PACKAGESERVICEID
INNER JOIN PACKAGE_ELEMENT PE ON PE.PACKAGEELEMENTID = PO.PACKAGEELEMENTID
INNER JOIN PACKAGE_ALLOCATION_MEMBERSHIP PAM ON PAM.PACKAGEELEMENTID = PE.PACKAGEELEMENTID

INNER JOIN PACKAGE_MASTER_ALLOCATION PMA ON PMA.PACKAGEMASTERALLOCATIONID = PAM.PACKAGEMASTERALLOCATIONID
INNER JOIN PACKAGE_ALLOCATION_DEPARTURE PAD ON PAD.PACKAGEMASTERALLOCATIONID = PMA.PACKAGEMASTERALLOCATIONID

