SELECT
PT.PACKAGETYPEID AS PackageID,
P.PACKAGELONGNAME AS Name,
P.PACKAGESHORTNAME AS ShortName,
PT.PACKAGETYPENAME AS PackageTypeName,
PS.PACKAGESTATUSNAME AS StatusName,
PS.PACKAGESTATUSCANBOOK AS IsActive,
O.ORGANISATIONNAME AS ORGANISATIONNAME,
O.ORGANISATIONDESCRIPTION AS Description,
P.PACKAGETERMSINCLUSIONS AS Inclusions,
P.PACKAGETERMSEXCLUSIONS AS Exclusions,
P.REGIONID AS Region1,
P.REGIONID2 Region2,
P.REGIONID3 Region3,
P.PACKAGEPICKUPTIME AS PickupTime,
P.PACKAGEDROPOFFTIME AS DropOffTime
FROM PACKAGE_TYPE PT
INNER JOIN PACKAGE P ON P.PACKAGETYPEID=PT.PACKAGETYPEID
INNER JOIN PACKAGE_STATUS PS ON PS.PACKAGESTATUSID=P.PACKAGESTATUSID
INNER JOIN ORGANISATION O ON O.ORGANISATIONID=P.ORGANISATIONID

SELECT * FROM PACKAGE_TYPE
SELECT * FROM PACKAGE
SELECT * FROM PACKAGE_STATUS
SELECT * FROM ORGANISATION
SELECT * FROM PACKAGE_ELEMENT

