SELECT 
P.PACKAGELONGNAME AS PackageName,
PID.PACKAGEITINERARYDAYID AS Day,
PID.PACKAGEITINERARYDAYDESCRIPTION AS DayDesc,
PII.PACKAGEITINERARYITEMID AS Item,
PII.PACKAGEITINERARYITEMSEQ AS ItemSeq,
PII.PACKAGEITINERARYITEMDESCRIPTION AS ItemDesc,
S.SERVICELONGNAME AS ServiceName,
STO.SERVICETYPEOPTIONNAME AS OptionName,
STE.SERVICETYPEEXTRANAME AS ExtraName,	
PO.PACKAGEOPTIONOPTIONAL IsOptional,	
PE.BASEDONPACKAGEELEMENTID AS ElementName,	
PO.PACKAGEOPTIONQUANTITY Qty,
PO.PACKAGEOPTIONNUMBEROFNIGHTS AS NoOfNights,
BOS.BOOKEDOPTIONSTATUSNAME AS StatusName,	
PO.PACKAGEOPTIONFROMDAYSEQ AS FromDay,	
PO.PACKAGEOPTIONTODAYSEQ AS ToDay,
PO.PACKAGEOPTIONSPLITPRICE AS SplitPrice,
P.SERVICE_AVAILABILITY AS IsActive
FROM PACKAGE P
INNER JOIN PACKAGE_ITINERARY_DAY PID ON PID.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_ITINERARY_ITEM PII ON PII.PACKAGEITINERARYDAYID = PID.PACKAGEITINERARYDAYID
INNER JOIN ASSIGNED_PACKAGE_SERVICE APS ON APS.PACKAGEITINERARYITEMID = PII.PACKAGEITINERARYITEMID
INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGESERVICEID = APS.PACKAGESERVICEID
INNER JOIN SERVICE S ON S.SERVICEID = PS.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.PACKAGESERVICEID = PS.PACKAGESERVICEID
INNER JOIN PACKAGE_ELEMENT PE ON PE.PACKAGEELEMENTID = PO.PACKAGEELEMENTID 
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = PE.SERVICETYPEOPTIONID
INNER JOIN SERVICE_TYPE_EXTRA STE ON STE.SERVICETYPEID = S.SERVICETYPEID
INNER JOIN BOOKED_OPTION_STATUS BOS ON BOS.BOOKEDOPTIONSTATUSID = PO.BOOKEDOPTIONSTATUSID


SELECT * FROM PACKAGE
SELECT * FROM ORGANISATION
SELECT * FROM PACKAGE_ELEMENT
SELECT * FROM PACKAGE_STATUS
SELECT * FROM PACKAGE_TYPE