SELECT *
--PACKAGEMASTERALLOCATIONID		
--DepartureDate		
--ReleasePeriod	
--TotalAvailable		
--TotalUsed	
--TotalUnitsAvailable		
--TotalUnitsUsed

FROM PACKAGE P
INNER JOIN PACKAGE_DEPARTURE PD ON PD.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGEDEPARTUREID = PD.PACKAGEDEPARTUREID
INNER JOIN SERVICE S ON S.SERVICEID = PS.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.PACKAGESERVICEID = PS.PACKAGESERVICEID
--INNER JOIN SERVICE_TYPE_OPTION STO ON STO.PACKAGEOPTIONID = PO.PACKAGEOPTIONID
INNER JOIN PACKAGE_ELEMENT PE ON PE.PACKAGEELEMENTID = PO.PACKAGEELEMENTID
INNER JOIN PACKAGE_ALLOCATION_MEMBERSHIP PAM ON PAM.PACKAGEELEMENTID = PE.PACKAGEELEMENTID
