SELECT 
P.PACKAGELONGNAME AS PackageName,	
PD.PACKAGEDEPARTUREID AS DEPARTUREID,
PD.PACKAGEDEPARTURENAME AS	DepartureName,
PD.PACKAGEDEPARTUREDATE AS Departure_Date,
PD.PACKAGEDEPARTUREREFERENCE AS	REREFERENCE,
PDS.PACKAGEDEPARTURESTATUSNAME AS StatusName,	
--IsActive
PD.SEATONBUS AS SOB,
PD.FIXEDDEPARTURE AS FIXED,
--NFD

PT.PACKAGETYPENAME AS PackageTypeName

FROM PACKAGE P
INNER JOIN PACKAGE_DEPARTURE PD ON P.PACKAGEID = PD.PACKAGEID
INNER JOIN PACKAGE_DEPARTURE_STATUS PDS ON PDS.PACKAGEDEPARTURESTATUSID = PD.PACKAGEDEPARTURESTATUSID
INNER JOIN PACKAGE_TYPE PT ON PT.PACKAGETYPEID = P.PACKAGETYPEID