SELECT 
P.PACKAGELONGNAME AS PackageName,	
PAM.PACKAGEMASTERALLOCATIONID AS PACKAGEMASTERALLOCATIONID,	
PMA.PACKAGEMASTERALLOCATIONOVERALLOCATED AS PACKAGEMASTERALLOCATIONOVERALLOCATED,	
PMA.ALLOCATIONNAMEID AS ALLOCATIONNAMEID,
--ALLOCATIONNAME	
PD.PACKAGEDEPARTUREDATE AS DepartureDate,	
S.ALLOCATIONRELEASETIME AS RELEASEPERIOD,	
PAD.PACKAGEALLOCATIONDEPARTURETOTALAVAILABLE AS DEPARTURETOTALAVAILABLE,	
PAD.PACKAGEALLOCATIONDEPARTURETOTALUSED AS DEPARTURETOTALUSED,	
PAD.PACKAGEALLOCATIONDEPARTURETOTALAVAILABLEUNITS AS TOTALAVAILABLEUNITS ,	
PAD.PACKAGEALLOCATIONDEPARTURETOTALUSEDUNITS AS DEPARTURETOTALUSEDUNITS,	
PAD.PACKAGEALLOCATIONDEPARTUREORIGINALPAX AS EPARTUREORIGINALPAX,	
PAD.PACKAGEALLOCATIONDEPARTUREORIGINALUNIT DEPARTUREORIGINALUNIT

FROM PACKAGE P
INNER JOIN PACKAGE_DEPARTURE PD ON PD.PACKAGEID = P.PACKAGEID
INNER JOIN PACKAGE_SERVICE PS ON PS.PACKAGEDEPARTUREID = PD.PACKAGEDEPARTUREID
INNER JOIN SERVICE S ON S.SERVICEID = PS.SERVICEID
INNER JOIN PACKAGE_OPTION PO ON PO.PACKAGESERVICEID =PS.PACKAGESERVICEID
--INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETID = PO.SERVICETYPEOPTIONID
INNER JOIN PACKAGE_ELEMENT PE ON PE.PACKAGEELEMENTID = PO.PACKAGEELEMENTID
INNER JOIN PACKAGE_ALLOCATION_MEMBERSHIP PAM ON PAM.PACKAGEELEMENTID = PE.PACKAGEELEMENTID
INNER JOIN PACKAGE_MASTER_ALLOCATION PMA ON PMA.PACKAGEMASTERALLOCATIONID = PAM.PACKAGEMASTERALLOCATIONID
INNER JOIN PACKAGE_ALLOCATION_DEPARTURE PAD ON PAD.PACKAGEMASTERALLOCATIONID = PMA.PACKAGEMASTERALLOCATIONID

