SELECT  
 S.SERVICELONGNAME
, AM.MASTERALLOCATIONID
, SOIS.SERVICEOPTIONINSERVICEID
, STO.SERVICETYPEOPTIONNAME
, MA.MASTERALLOCATIONFREESELLSALE
, MA.MASTERALLOCATIONFREESELLSALEOVERRIDE
, MA.MASTERALLOCATIONSTARTDATE
, MA.MASTERALLOCATIONENDDATE
, MA.MASTERALLOCATIONDAYMONDAY 
, MA.MASTERALLOCATIONDAYTUESDAY  
, MA.MASTERALLOCATIONDAYWEDNESDAY 
, MA.MASTERALLOCATIONDAYTHURSDAY 
, MA.MASTERALLOCATIONDAYFRIDAY 
, MA.MASTERALLOCATIONDAYSATURDAY 
, MA.MASTERALLOCATIONDAYSUNDAY
, A.ALLOCATIONDAYMONDAY 
, A.ALLOCATIONDAYTUESDAY 
, A.ALLOCATIONDAYWEDNESDAY 
, A.ALLOCATIONDAYTHURSDAY 
, A.ALLOCATIONDAYFRIDAY 
, A.ALLOCATIONDAYSATURDAY 
, A.ALLOCATIONDAYSUNDAY 
, MA.MASTERALLOCATIONRELEASEPERIODMON 
, MA.MASTERALLOCATIONRELEASEPERIODTUE 
, MA.MASTERALLOCATIONRELEASEPERIODWED 
, MA.MASTERALLOCATIONRELEASEPERIODTHU 
, MA.MASTERALLOCATIONRELEASEPERIODFRI 
, MA.MASTERALLOCATIONRELEASEPERIODSAT 
, MA.MASTERALLOCATIONRELEASEPERIODSUN 

FROM [SERVICE] S
INNER JOIN SERVICE_OPTION_IN_SERVICE SOIS ON SOIS.SERVICEID = S.SERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID = SOIS.SERVICETYPEOPTIONID
INNER JOIN SERVICE_OPTION_STATUS SOS ON SOS.SERVICEOPTIONSTATUSID = SOIS.SERVICEOPTIONSTATUSID
INNER JOIN PRICE P ON P.SERVICEOPTIONINSERVICEID = SOIS.SERVICEOPTIONINSERVICEID
--GET THE ALLOCATION DETAILS
INNER JOIN ALLOCATION_MEMBERSHIP AM ON AM.SERVICEOPTIONINSERVICEID = SOIS.SERVICEOPTIONINSERVICEID
INNER JOIN MASTER_ALLOCATION MA ON MA.MASTERALLOCATIONID = AM.MASTERALLOCATIONID 
INNER JOIN ALLOCATION A ON A.MASTERALLOCATIONID = MA.MASTERALLOCATIONID
