SELECT 
B.BOOKINGREFERENCENUMBER AS BOOKINGRef,
BS.BOOKEDSERVICEID,
S.SERVICELONGNAME AS SERVICEName,
B.BOOKINGTOTALCOSTAMOUNT AS BOOKEDSERVICETOTALCOSTAMOUNT,
B.BOOKINGTOTALSELLINGAMOUNT AS BOOKEDSERVICETOTALSELLINGAMOUNT,
BS.BOOKEDSERVICECLOSED AS BookedServiceClosed,
BS.QUOTEDSERVICEID AS QUOTEDSERVICEID

FROM BOOKING B
INNER JOIN BOOKED_SERVICE BS ON BS.BOOKINGID = B.BOOKINGID
INNER JOIN SERVICE S ON S.SERVICEID = BS.SERVICEID
