SELECT
B.BOOKINGID AS BOOKINGID,
BP.BOOKEDPACKAGEID AS BOOKEDPACKAGEID,
PD.PACKAGEDEPARTURENAME AS PACKAGEDEPARTUREName,
BP.BOOKEDPACKAGEWAITLISTED AS BOOKEDPACKAGEWAITLISTED 
FROM BOOKING B

INNER JOIN BOOKED_PACKAGE BP ON BP.BOOKINGID = B.BOOKINGID
INNER JOIN PACKAGE_DEPARTURE PD ON PD.PACKAGEDEPARTUREID =BP.PACKAGEDEPARTUREID
