SELECT 
BOOKINGID, 
B.BOOKINGREFERENCENUMBER AS RefNo, 
B.BOOKINGNAME AS BOOKINGNAME,
B.BOOKINGPREFIXID,
BS.BOOKINGSTATUSNAME AS BOOKINGSTATUSName,
B.BOOKINGBOOKINGDATE AS BookingDate,
B.BOOKINGSTARTDATE AS BOOKINGSTARTDATE,
B.BOOKINGENDDATE AS BOOKINGENDDATE,
B.BOOKINGEXPIRYDATE,
B.BOOKINGNUMBEROFNIGHTS,
CL.CLIENTNAME AS CLIENTName,
B.BOOKINGCLIENTREFERENCENUMBER AS CLIENTREFNUMBER,
BT.BOOKINGTYPENAME AS BOOKINGTYPEName,
PT.PRICETYPENAME AS PRICETYPEName,
C.CURRENCYISOCODE AS CURRENCYISOCode,
B.BOOKINGTOTALCOSTAMOUNT AS BOOKINGTOTALCOSTAMOUNT,
B.BOOKINGTOTALSELLINGAMOUNT AS BOOKINGTOTALSELLINGAMOUNT,
B.QUOTEID AS QUOTEID,
CS.COMMISSIONSCHEMENAME AS COMMISSIONSCHEMENAME,
CP.CANCELLATIONPOLICYNAME AS CANCELLATIONPOLICYName

FROM BOOKING B
INNER JOIN BOOKING_STATUS BS ON BS.BOOKINGSTATUSID = B.BOOKINGSTATUSID
INNER JOIN BOOKING_TYPE BT ON BT.BOOKINGTYPEID = B.BOOKINGTYPEID
INNER JOIN PRICE_TYPE PT ON PT.PRICETYPEID = B.PRICETYPEID
INNER JOIN CURRENCY C ON C.CURRENCYID = B.CURRENCYID
INNER JOIN CLIENT CL ON CL.CLIENTID = B.CLIENTID
INNER JOIN COMMISSION_SCHEME CS ON CS.COMMISSIONSCHEMEID = B.COMMISSIONSCHEMEID
INNER JOIN CANCELLATION_POLICY CP ON CP.CANCELLATIONPOLICYID = B.CANCELLATIONPOLICYID