SELECT  
B.BOOKINGID AS BOOKINGID,
PT.PASSENGERTYPENAME AS PASSENGERTYPEname,
P.PASSENGERID AS PASSENGERID,
P.PASSENGERFIRSTNAME AS Name,
P.PASSENGERAGE AS AGE,
P.PASSENGERDATEOFBIRTH AS DOB,
P.SEXID AS Gender,
P.PASSENGERLOGICALROOMID AS PASSENGERLOGICALROOMID,
OT.OCCUPANCYTYPENAME AS OCCUPANCYTYPEName,
AP.ASSIGNEDPASSENGERID AS ASSIGNEDPASSENGERID,
--B.BOOKINGNAME AS BOOKEDOPTIONName, 
R.ROOMID AS ROOMID, 
AP.ELEMENTPASSENGERID AS ELEMENTPASSENGERID,
AP.ISCHILD AS ISCHILD 
FROM BOOKING B

INNER JOIN BOOKED_PACKAGE BP ON BP.BOOKINGID = B.BOOKINGID
INNER JOIN BOOKED_SERVICE BS ON BS.BOOKINGID = B.BOOKINGID
INNER JOIN BOOKED_OPTION BO ON BO.BOOKEDSERVICEID = BS.BOOKEDSERVICEID
INNER JOIN PASSENGER_TYPE PT ON PT.PASSENGERTYPEID = BO.PASSENGERTYPEID
INNER JOIN ASSIGNED_PASSENGER AP ON AP.BOOKEDOPTIONID = BO.BOOKEDOPTIONID
INNER JOIN PASSENGER P ON P.PASSENGERID =AP.PASSENGERID
INNER JOIN SEX S ON S.SEXID = P.SEXID
INNER JOIN ROOM R ON R.ROOMID = AP.ROOMID 
INNER JOIN OCCUPANCY_TYPE OT ON OT.OCCUPANCYTYPEID = AP.OCCUPANCYTYPEID