select
S.SERVICELONGNAME AS ServiceName,
STO.SERVICETYPEOPTIONNAME AS OptionName,	
P.PRICEBUYING   IsBuying,	
BT.BOOKINGTYPENAME AS BookingTypeName	,
PT.PRICETYPENAME AS  PriceTypeName,	
CD.CONTRACTDURATIONID AS ContractDurationID	,
ST.SEASONTYPENAME  SeasonTypeName	,
CD.CONTRACTDURATIONSTARTDATE AS FromDate	,
CD.CONTRACTDURATIONENDDATE AS ToDate	,
P.PRICEDAYMONDAY AS  Mon	,
P.PRICEDAYTUESDAY AS Tue	,
P.PRICEDAYWEDNESDAY AS Wed,	
P.PRICEDAYTHURSDAY AS Thu	,
P.PRICEDAYFRIDAY AS  Fri	,
P.PRICEDAYSATURDAY AS Sat	,
P.PRICEDAYSUNDAY AS Sun	,
P. PriceID	,
C.CURRENCYISOCODE AS CurrencyISO	,
P.PRICEAMOUNT AS Amount	,
P.PRICEAMOUNTVALIDATED Verified	,
CP.CHARGINGPOLICYNAME ChargingPolicyName	,	
CPO.CHILDPOLICYNAME  ChildPolicyName

from SERVICE S
INNER JOIN  SERVICE_OPTION_IN_SERVICE SOIN ON SOIN.SERVICEID= S.SERVICEID
INNER JOIN SERVICE_TYPE_OPTION STO ON STO.SERVICETYPEOPTIONID= SOIN.SERVICETYPEOPTIONID
INNER JOIN PRICE P ON P.SERVICEOPTIONINSERVICEID= SOIN.SERVICEOPTIONINSERVICEID
INNER JOIN BOOKING_TYPE BT ON BT.BOOKINGTYPEID= P.BOOKINGTYPEID
INNER JOIN PRICE_TYPE PT ON PT.PRICETYPEID= P.PRICETYPEID
INNER JOIN CONTRACT_DURATION CD ON CD.CONTRACTDURATIONID =P.CONTRACTDURATIONID
INNER JOIN SEASON_TYPE ST ON ST.SEASONTYPEID = P.SEASONTYPEID
INNER JOIN CURRENCY C ON C.CURRENCYID= P.CURRENCYID
INNER JOIN ASSIGNED_CHARGING_POLICY ACPO ON ACPO.SERVICETYPEOPTIONID= STO.SERVICETYPEOPTIONID
INNER JOIN CHARGING_POLICY CP ON CP.CHARGINGPOLICYID = ACPO.CHARGINGPOLICYID
INNER JOIN CHILD_POLICY CPO ON CPO.CHILDPOLICYID = P.CHILDPOLICYID

;

SELECT * FROM SERVICE
SELECT * FROM SERVICE_TYPE_OPTION
SELECT * FROM CURRENCY
SELECT * FROM SERVICE
SELECT * FROM SERVICE
SELECT * FROM SERVICE
SELECT * FROM PRICE
SELECT * FROM CONTRACT_DURATION
SELECT * FROM  PRICE_TYPE


